# correlation
1. formula
$$
    corr(X,Y) = \frac{cov(X,Y)}{\sigma_{X}\sigma_{Y}} = \frac{\Sigma_{i}^{n}{(X_i-\bar X)(Y_i- \bar Y)}}{\sqrt{\Sigma_{i}^{n}{(X_i-\bar X)^2}}\sqrt{\Sigma_{i}^{n}{(Y_i-\bar Y)^2}}}
$$
2. numpy knowledge
    > 1. one-dimensional array could not use T (transpose) method, use reshape(n,-1) instead <br>
    > 2. broadcast functionality
    > 3. <font color=red> np.cov( ) np.corrcoef(  ) </font>

In [3]:
import numpy as np
import pandas as pd
import math
from sklearn.datasets import load_iris

In [5]:
# generate a set of data
iris_data, iris_label = load_iris(return_X_y=True)
iris_data.shape

(150, 4)

In [36]:
# covariance calculation

iris_miu = iris_data - iris_data.mean(axis=0)
iris_cov = np.dot(iris_miu.T,iris_miu)/iris_data.shape[0]
iris_cov

array([[ 0.68112222, -0.04215111,  1.26582   ,  0.51282889],
       [-0.04215111,  0.18871289, -0.32745867, -0.12082844],
       [ 1.26582   , -0.32745867,  3.09550267,  1.286972  ],
       [ 0.51282889, -0.12082844,  1.286972  ,  0.57713289]])

In [53]:
# correlation calculation
# use broadcast feature, vertically once and horizontally once

iris_sigma = np.diag(iris_cov)
iris_std = np.sqrt(iris_sigma)
iris_corr = np.divide(np.divide(iris_cov,iris_std),iris_std.reshape(4,-1))
iris_corr

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [39]:
# using function method
np.cov(iris_data.T)

array([[ 0.68569351, -0.042434  ,  1.27431544,  0.51627069],
       [-0.042434  ,  0.18997942, -0.32965638, -0.12163937],
       [ 1.27431544, -0.32965638,  3.11627785,  1.2956094 ],
       [ 0.51627069, -0.12163937,  1.2956094 ,  0.58100626]])

In [40]:
# using function method
np.corrcoef(iris_data.T)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])